source 'https://rubygems.org'
gem 'tmuxinator'
gem 'graph'
#gem 'gem-toolbox'
gem 'gem-man'
gem 'gem-orphan'
gem 'gem_info'
gem 'zeus'
gem 'pry'
# gem 'pry-plus'
# gem 'pry-vterm_aliases'
gem 'rails-env-switcher'
gem 'pry-theme'
gem 'landscape'
