# frozen_string_literal: true

source 'https://rubygems.org'
gem 'graph'
gem 'tmuxinator'
# gem 'gem-toolbox'
gem 'gem-man'
gem 'gem-orphan'
gem 'gem_info'
gem 'pry'
gem 'zeus'
# gem 'pry-plus'
# gem 'pry-vterm_aliases'
gem 'amazing_print'
gem 'pry-theme'
gem 'rails-env-switcher'
gem 'terraform_landscape'
gem 'aws-sdk', '~> 3'
gem 'neovim'
gem 'bundle-audit'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rails'
gem 'rubocop-rspec'
gem 'rubocop-thread_safety'
gem 'rubocop-require_tools'
gem 'rubocop-rake'
gem 'solargraph'
gem 'overcommit'
