# frozen_string_literal: true

source 'https://rubygems.org'
gem 'graph'
gem 'tmuxinator'
# gem 'gem-toolbox'
gem 'gem-man'
gem 'gem-orphan'
gem 'gem_info'
gem 'pry'
gem 'zeus'
# gem 'pry-plus'
# gem 'pry-vterm_aliases'
gem 'awesome_print'
gem 'pry-theme'
gem 'rails-env-switcher'
gem 'terraform_landscape'
gem 'aws-sdk', '~> 3'
